/*
DESC USER_INFORMATION
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 USER_ID					    VARCHAR2(100)
 FIRST_NAME					    VARCHAR2(100)
 LAST_NAME					    VARCHAR2(100)
 YEAR_OF_BIRTH					    NUMBER(38)
 MONTH_OF_BIRTH 				    NUMBER(38)
 DAY_OF_BIRTH					    NUMBER(38)
 GENDER 					    VARCHAR2(100)
 CURRENT_CITY					    VARCHAR2(100)
 CURRENT_STATE					    VARCHAR2(100)
 CURRENT_COUNTRY				    VARCHAR2(100)
 HOMETOWN_CITY					    VARCHAR2(100)
 HOMETOWN_STATE 				    VARCHAR2(100)
 HOMETOWN_COUNTRY				    VARCHAR2(100)
 INSTITUTION_NAME				    VARCHAR2(100)
 PROGRAM_YEAR					    NUMBER(38)
 PROGRAM_CONCENTRATION				    CHAR(100)
 PROGRAM_DEGREE 				    VARCHAR2(100)

 CREATE TABLE USERS (
	USER_ID				NUMBER,
	FIRST_NAME			VARCHAR2(100) 	NOT NULL,
	LAST_NAME 			VARCHAR2(100)	NOT NULL,
	YEAR_OF_BIRTH		INTEGER,
	MONTH_OF_BIRTH 		INTEGER,
	DAY_OF_BIRTH		INTEGER,
	GENDER 				VARCHAR2(100),

CREATE TABLE USER_CURRENT_CITY (
	USER_ID 			NUMBER,
	CURRENT_CITY_ID 	INTEGER,

CREATE TABLE USER_HOMETOWN_CITY (
	USER_ID 			NUMBER,
	HOMETOWN_CITY_ID 	INTEGER,

CREATE TABLE CITIES (
	CITY_ID  			INTEGER,
	CITY_NAME 			VARCHAR2(100),
	STATE_NAME			VARCHAR2(100),
	COUNTRY_NAME		VARCHAR2(100),
	PRIMARY KEY (CITY_ID)

CREATE TABLE PROGRAMS (
	PROGRAM_ID 			INTEGER,
	INSTITUTION			VARCHAR(100),
	CONCENTRATION		VARCHAR(100),
	DEGREE 				VARCHAR(100),

	CREATE TABLE EDUCATION (
	USER_ID 			NUMBER,
	PROGRAM_ID 			INTEGER,
	PROGRAM_YEAR		INTEGER,
*/

CREATE VIEW VIEW_USER_INFORMATION (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER,
								   CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY, HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY,
								   INSTITUTION_NAME, PROGRAM_YEAR, PROGRAM_CONCENTRATION, PROGRAM_DEGREE) AS
	(SELECT CAST(U.USER_ID AS VARCHAR2(100)), U.FIRST_NAME, U.LAST_NAME, CAST(U.YEAR_OF_BIRTH AS NUMBER(38)), CAST(U.MONTH_OF_BIRTH AS NUMBER(38)),
		CAST(U.DAY_OF_BIRTH AS NUMBER(38)), U.GENDER, C.CITY_NAME, C.STATE_NAME, C.COUNTRY_NAME, CH.CITY_NAME, CH.STATE_NAME, CH.COUNTRY_NAME,
		CAST(P.INSTITUTION AS VARCHAR2(100)), CAST(E.PROGRAM_YEAR AS NUMBER(38)), CAST(P.CONCENTRATION AS CHAR(100)), CAST(P.DEGREE AS VARCHAR2(100))
		FROM USERS U
		FULL JOIN EDUCATION E ON (U.USER_ID = E.USER_ID)
		LEFT OUTER JOIN PROGRAMS P ON (E.PROGRAM_ID = P.PROGRAM_ID)
		LEFT OUTER JOIN USER_CURRENT_CITY UC ON (U.USER_ID = UC.USER_ID)
		LEFT OUTER JOIN USER_HOMETOWN_CITY UH ON (U.USER_ID = UH.USER_ID)
		FULL JOIN CITIES C ON (UC.CURRENT_CITY_ID = C.CITY_ID)
		FULL JOIN CITIES CH ON (UH.HOMETOWN_CITY_ID = CH.CITY_ID));

/*
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 USER1_ID					    VARCHAR2(100)
 USER2_ID					    VARCHAR2(100)
*/
CREATE VIEW VIEW_ARE_FRIENDS (USER1_ID, USER2_ID) AS 
	(SELECT CAST(USER1_ID AS VARCHAR2(100)), CAST(USER2_ID AS VARCHAR2(100))
	 FROM FRIENDS);


/*
Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 ALBUM_ID					    VARCHAR2(100)
 OWNER_ID					    VARCHAR2(100)
 COVER_PHOTO_ID 				    VARCHAR2(100)
 ALBUM_NAME					    VARCHAR2(100)
 ALBUM_CREATED_TIME				    TIMESTAMP(6)
 ALBUM_MODIFIED_TIME				    TIMESTAMP(6)
 ALBUM_LINK					    VARCHAR2(2000)
 ALBUM_VISIBILITY				    VARCHAR2(100)
 PHOTO_ID					    VARCHAR2(100)
 PHOTO_CAPTION					    VARCHAR2(2000)
 PHOTO_CREATED_TIME				    TIMESTAMP(6)
 PHOTO_MODIFIED_TIME				    TIMESTAMP(6)
 PHOTO_LINK					    VARCHAR2(2000)
 */
CREATE VIEW VIEW_PHOTO_INFORMATION (ALBUM_ID, OWNER_ID, COVER_PHOTO_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME,
	ALBUM_LINK, ALBUM_VISIBILITY, PHOTO_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK) AS
	(SELECT CAST(A.ALBUM_ID AS VARCHAR2(100)), CAST(A.ALBUM_OWNER_ID AS VARCHAR2(100)),  CAST(A.COVER_PHOTO_ID AS VARCHAR2(100)),
		CAST(A.ALBUM_NAME AS VARCHAR2(100)), CAST(A.ALBUM_CREATED_TIME AS TIMESTAMP(6)), CAST(A.ALBUM_MODIFIED_TIME AS TIMESTAMP(6)),
		A.ALBUM_LINK, CAST(A.ALBUM_VISIBILITY AS VARCHAR2(100)), CAST(P.PHOTO_ID AS VARCHAR2(100)), CAST(P.PHOTO_CAPTION AS VARCHAR2(2000)),
		CAST(P.PHOTO_CREATE_TIME AS TIMESTAMP(6)), CAST(P.PHOTO_MODIFIED_TIME AS TIMESTAMP(6)), CAST(P.PHOTO_LINK AS VARCHAR2(2000))
	FROM ALBUMS A, PHOTOS P
	WHERE A.ALBUM_ID = P.ALBUM_ID);

/*
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 PHOTO_ID					    VARCHAR2(100)
 TAG_SUBJECT_ID 				    VARCHAR2(100)
 TAG_CREATED_TIME				    TIMESTAMP(6)
 TAG_X_COORDINATE				    NUMBER
 TAG_Y_COORDINATE				    NUMBER

 CREATE TABLE TAGS (
/*  NAME 				TYPE			NULL?		
	TAG_PHOTO_ID		VARCHAR(100),
	TAG_SUBJECT_ID		NUMBER,
	TAG_CREATE_TIME		TIMESTAMP		NOT NULL,
	TAG_X				NUMBER			NOT NULL,
	TAG_Y				NUMBER			NOT NULL,

 */
CREATE VIEW VIEW_TAG_INFORMATION (PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE) AS
	(SELECT TAG_PHOTO_ID, CAST(TAG_SUBJECT_ID AS VARCHAR2(100)), CAST(TAG_CREATE_TIME AS TIMESTAMP(6)), TAG_X, TAG_Y
		FROM TAGS);

/*
 Name					   Null?    Type
 ----------------------------------------- -------- ----------------------------
 EVENT_ID					    VARCHAR2(100)
 EVENT_CREATOR_ID				    VARCHAR2(100)
 EVENT_NAME					    VARCHAR2(100)
 EVENT_TAGLINE					    VARCHAR2(1000)
 EVENT_DESCRIPTION				    VARCHAR2(4000)
 EVENT_HOST					    VARCHAR2(100)
 EVENT_TYPE					    VARCHAR2(100)
 EVENT_SUBTYPE					    VARCHAR2(100)
 EVENT_LOCATION 				    VARCHAR2(200)
 EVENT_CITY					    VARCHAR2(100)
 EVENT_STATE					    VARCHAR2(100)
 EVENT_COUNTRY					    VARCHAR2(100)
 EVENT_START_TIME				    TIMESTAMP(6)
 EVENT_END_TIME 				    TIMESTAMP(6)

 CREATE TABLE USER_EVENTS (
	EVENT_ID			NUMBER,
	EVENT_CREATOR_ID	NUMBER			NOT NULL,
	EVENT_NAME			VARCHAR(100)	NOT NULL,
	EVENT_TAGLINE		VARCHAR(100),
	EVENT_DESCRIPTION	VARCHAR(100),
	EVENT_HOST			VARCHAR(100)	NOT NULL,
	EVENT_TYPE			VARCHAR(100)	NOT NULL,
	EVENT_SUBTYPE		VARCHAR(100)	NOT NULL,
	EVENT_LOCATION		VARCHAR(100),
	EVENT_CITY_ID		INTEGER,
	EVENT_START_TIME	TIMESTAMP		NOT NULL,
	EVENT_END_TIME 		TIMESTAMP		NOT NULL,

CREATE TABLE CITIES (
	CITY_ID  			INTEGER,
	CITY_NAME 			VARCHAR2(100),
	STATE_NAME			VARCHAR2(100),
	COUNTRY_NAME		VARCHAR2(100),
	PRIMARY KEY (CITY_ID)
 */
CREATE VIEW VIEW_EVENT_INFORMATION (EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE,
									EVENT_SUBTYPE, EVENT_LOCATION, EVENT_CITY, EVENT_STATE, EVENT_COUNTRY, EVENT_START_TIME, EVENT_END_TIME) AS
	(SELECT CAST(E.EVENT_ID AS VARCHAR2(100)), CAST(E.EVENT_CREATOR_ID AS VARCHAR2(100)), CAST(E.EVENT_NAME AS VARCHAR2(100)),
		CAST(E.EVENT_TAGLINE AS VARCHAR2(1000)), CAST(E.EVENT_DESCRIPTION AS VARCHAR2(4000)), CAST(E.EVENT_HOST AS VARCHAR2(100)),
		CAST(E.EVENT_TYPE AS VARCHAR2(100)), CAST(E.EVENT_SUBTYPE AS VARCHAR2(100)), CAST(E.EVENT_LOCATION AS VARCHAR2(200)),
		CAST(C.CITY_NAME AS VARCHAR2(200)), CAST(C.STATE_NAME AS VARCHAR2(100)), CAST(C.COUNTRY_NAME AS VARCHAR2(100)),
		CAST(E.EVENT_START_TIME AS TIMESTAMP(6)), CAST(E.EVENT_END_TIME AS TIMESTAMP(6))
		FROM USER_EVENTS E, CITIES C
		WHERE E.EVENT_CITY_ID = C.CITY_ID);




