/* FOREIGN KEY CONSTRAINT SHOULD DELETE THESE TABLES:
	FRIENDS
	USER_CURRENT_CITY
	USER_HOMETOWN_CITY
	MESSAGE
	EDUCATION
	PROGRAM
	USER_EVENT
	PARTICIPANTS
	ALBUM
		PHOTO
	TAG
*/

DROP TABLE FRIENDS;
DROP TABLE USER_CURRENT_CITY;
DROP TABLE USER_HOMETOWN_CITY;
DROP TABLE MESSAGE;
DROP TABLE EDUCATION;
DROP TABLE PROGRAMS;
DROP TABLE PARTICIPANTS;
DROP TABLE USER_EVENTS;
DROP TABLE TAGS;
ALTER TABLE ALBUMS DROP CONSTRAINT CV_ID_REFS_PHOTOS;
DROP SEQUENCE city_id_seq;
DROP SEQUENCE program_id_seq;
DROP SEQUENCE message_id_seq;
DROP TABLE PHOTOS;
DROP TABLE ALBUMS;
DROP TABLE CITIES;
DROP TABLE USERS; 





