CREATE TABLE PUBLIC_USERS AS (SELECT * FROM keykholt.PUBLIC_USER_INFORMATION);
CREATE TABLE PUBLIC_FRIENDS AS (SELECT * FROM keykholt.PUBLIC_ARE_FRIENDS);
CREATE TABLE PUBLIC_PHOTO_INFO AS (SELECT * FROM keykholt.PUBLIC_PHOTO_INFORMATION);
CREATE TABLE PUBLIC_TAG_INFO AS (SELECT * FROM keykholt.PUBLIC_TAG_INFORMATION);
CREATE TABLE PUBLIC_EVENT_INFO AS (SELECT * FROM keykholt.PUBLIC_EVENT_INFORMATION);


INSERT INTO USERS(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER),
	SELECT(USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER),
		FROM PUBLIC_USERS

INSERT INTO CITY()