/*
CREATE TABLE PUBLIC_USERS AS (SELECT * FROM keykholt.PUBLIC_USER_INFORMATION);
CREATE TABLE PUBLIC_FRIENDS AS (SELECT * FROM keykholt.PUBLIC_ARE_FRIENDS);
CREATE TABLE PUBLIC_PHOTO_INFO AS (SELECT * FROM keykholt.PUBLIC_PHOTO_INFORMATION);
CREATE TABLE PUBLIC_TAG_INFO AS (SELECT * FROM keykholt.PUBLIC_TAG_INFORMATION);
CREATE TABLE PUBLIC_EVENT_INFO AS (SELECT * FROM keykholt.PUBLIC_EVENT_INFORMATION);
*/


/*----------- USER TABLE -----------*/
INSERT INTO USERS (USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER) 
	(SELECT DISTINCT (USER_ID), FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER 
		FROM keykholt.PUBLIC_USER_INFORMATION);

/*----------- FRIENDS TABLE --------------*/

/*INSERT INTO FRIENDS (USER1_ID, USER2_ID)
	(SELECT USER1_ID, USER2_ID FROM keykholt.PUBLIC_ARE_FRIENDS
		WHERE 
		)
*/

/*----------- CITIES TABLE ------------*/
INSERT INTO CITIES (CITY_NAME, STATE_NAME, COUNTRY_NAME)
	(SELECT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY
		FROM keykholt.PUBLIC_USER_INFORMATION
	UNION 
	SELECT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY
		FROM keykholt.PUBLIC_USER_INFORMATION
	UNION
	SELECT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY
		FROM keykholt.PUBLIC_EVENT_INFORMATION);

/*--------- USER CURRENT CITY --------*/




